import type { Deal } from '@shared/types/deals';
import type { LocationFilter } from '@/types/deals';
import type { DealTypeFilter } from '@/components/deals/DealsToolbar';

// Dev-only fixtures for the /deals-preview harness — no backend required. `MOCK_USER_ID` is "you",
// so scope=mine and the owner tools have something to key off in the preview.
export const MOCK_USER_ID = 'preview-me';

function daysAgo(n: number): string {
    return new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString();
}

function img(seed: string): string {
    // picsum returns a stable photo per seed — enough to exercise the loaded-image path in preview.
    return `https://picsum.photos/seed/${seed}/640/360`;
}

export const MOCK_DEALS: Deal[] = [
    {
        id: 1,
        createdAt: daysAgo(0),
        msaId: 1,
        msaName: 'San Diego-Chula Vista-Carlsbad, CA',
        userId: 'user-a',
        userFirstName: 'Marcus',
        userLastName: 'Bell',
        userEmail: 'marcus@example.com',
        userPhone: '(619) 555-0142',
        links: [
            { url: 'https://www.redfin.com/CA/San-Diego/123-Main', domain: 'redfin' },
            { url: 'https://www.zillow.com/homedetails/123-main', domain: 'zillow' },
        ],
        photosUrl: 'https://photos.example.com/123-main',
        streetViewUrl: img('sd-main'),
        isArvExclusive: true,
        address: '4821 Cape May Ave',
        city: 'SAN DIEGO',
        state: 'CA',
        zipCode: '92107',
        dealType: 'wholesale',
        price: 620000,
        potentialARV: 845000,
        estimatedBudget: 95000,
        beds: 3,
        baths: 2,
        sqft: 1420,
        propertyType: 'Single Family',
        showingTime: '2026-07-16T14:00:00',
        notes: 'Ocean Beach cosmetic flip — original 1950s bones, needs kitchen + baths and a roof. Comps two blocks north closing at $860–890K. Motivated seller, quick close preferred.',
        bidCount: 4,
    },
    {
        id: 2,
        createdAt: daysAgo(1),
        msaId: 2,
        msaName: 'Miami-Fort Lauderdale-Pompano Beach, FL',
        userId: 'user-b',
        userFirstName: 'Diana',
        userLastName: 'Ruiz',
        userEmail: 'diana@example.com',
        links: [{ url: 'https://www.redfin.com/FL/Miami/88-oak', domain: 'redfin' }],
        streetViewUrl: img('mia-oak'),
        isArvExclusive: false,
        address: '88 NW 42nd St',
        city: 'MIAMI',
        state: 'FL',
        zipCode: '33127',
        dealType: 'agent',
        price: 410000,
        potentialARV: 560000,
        estimatedBudget: 70000,
        beds: 4,
        baths: 2,
        sqft: 1680,
        propertyType: 'Single Family',
        notes: 'Wynwood-adjacent, strong rental demand. Listing agent open to assignable contract.',
        bidCount: 0,
    },
    {
        id: 3,
        createdAt: daysAgo(2),
        msaId: 3,
        msaName: 'Denver-Aurora-Lakewood, CO',
        userId: MOCK_USER_ID,
        userFirstName: 'You',
        userLastName: '',
        userEmail: 'you@example.com',
        links: [],
        streetViewUrl: img('den-pine'),
        isArvExclusive: false,
        address: '1290 S Pearl St',
        city: 'DENVER',
        state: 'CO',
        zipCode: '80210',
        dealType: 'reo',
        price: 385000,
        potentialARV: null,
        estimatedBudget: null,
        beds: 2,
        baths: 1,
        sqft: 980,
        propertyType: 'Townhouse',
        notes: 'Bank-owned, sold as-is. ARV pending our own comp pull.',
        bidCount: 2,
    },
    {
        id: 4,
        createdAt: daysAgo(3),
        msaId: 4,
        msaName: 'Los Angeles-Long Beach-Anaheim, CA',
        userId: 'user-c',
        userFirstName: 'Priya',
        userLastName: 'Anand',
        userEmail: 'priya@example.com',
        userPhone: '(213) 555-0199',
        links: [
            { url: 'https://www.zillow.com/homedetails/undisclosed', domain: 'zillow' },
            { url: 'https://www.propstream.com/deal', domain: 'propstream' },
        ],
        streetViewUrl: null,
        isArvExclusive: true,
        city: 'LOS ANGELES',
        state: 'CA',
        zipCode: '90042',
        dealType: 'wholesale',
        price: 720000,
        potentialARV: 1050000,
        estimatedBudget: 140000,
        beds: 3,
        baths: 2,
        sqft: 1560,
        propertyType: 'Single Family',
        notes: 'Highland Park — off-market, address disclosed to serious buyers on request.',
        onBehalfOfEmail: 'client@investors.com',
        adminNotes: 'Seller is a repeat ARV client; prioritize.',
        bidCount: 7,
    },
    {
        id: 5,
        createdAt: daysAgo(5),
        msaId: 5,
        msaName: 'San Francisco-Oakland-Berkeley, CA',
        userId: 'user-d',
        userFirstName: 'Tom',
        userLastName: 'Okafor',
        userEmail: 'tom@example.com',
        links: [{ url: 'https://www.redfin.com/CA/Oakland/sold', domain: 'redfin' }],
        streetViewUrl: img('sf-elm'),
        isArvExclusive: false,
        address: '3140 Fruitvale Ave',
        city: 'OAKLAND',
        state: 'CA',
        zipCode: '94602',
        dealType: 'sold',
        price: 815000,
        potentialARV: 940000,
        beds: 3,
        baths: 2,
        sqft: 1490,
        propertyType: 'Single Family',
        notes: 'Closed comp — full gut, sold 9 days after relist. Good margin reference for the area.',
    },
    {
        id: 6,
        createdAt: daysAgo(6),
        msaId: 2,
        msaName: 'Miami-Fort Lauderdale-Pompano Beach, FL',
        userId: 'user-e',
        userFirstName: 'Lena',
        userLastName: 'Cho',
        userEmail: 'lena@example.com',
        links: [],
        streetViewUrl: img('mia-bay'),
        isArvExclusive: false,
        address: '210 Bayshore Dr',
        city: 'FORT LAUDERDALE',
        state: 'FL',
        zipCode: '33304',
        dealType: 'agent',
        price: 690000,
        potentialARV: 660000,
        estimatedBudget: 40000,
        beds: 3,
        baths: 3,
        sqft: 1720,
        propertyType: 'Condo',
        notes: 'Priced above recent comps — including it to show a thin/negative spread in the feed.',
        bidCount: 0,
    },
    {
        id: 7,
        createdAt: daysAgo(9),
        msaId: 6,
        msaName: 'Port St. Lucie, FL',
        userId: 'user-f',
        userFirstName: 'Sam',
        userLastName: 'Reyes',
        userEmail: 'sam@example.com',
        links: [],
        streetViewUrl: null,
        isArvExclusive: false,
        address: '556 SW Ray Ave',
        city: 'PORT ST. LUCIE',
        state: 'FL',
        zipCode: '34953',
        dealType: 'wholesale',
        price: null,
        potentialARV: null,
        beds: 3,
        baths: 2,
        sqft: 1340,
        propertyType: 'Single Family',
        notes: 'Wholesaler still finalizing numbers — pricing to follow. Shows the "not disclosed" state.',
        bidCount: 1,
    },
    {
        id: 8,
        createdAt: daysAgo(12),
        msaId: 1,
        msaName: 'San Diego-Chula Vista-Carlsbad, CA',
        userId: MOCK_USER_ID,
        userFirstName: 'You',
        userLastName: '',
        userEmail: 'you@example.com',
        links: [{ url: 'https://www.redfin.com/CA/Chula-Vista/sold-2', domain: 'redfin' }],
        streetViewUrl: img('sd-sold'),
        isArvExclusive: true,
        address: '765 Third Ave',
        city: 'CHULA VISTA',
        state: 'CA',
        zipCode: '91910',
        dealType: 'sold',
        price: 540000,
        potentialARV: 705000,
        beds: 4,
        baths: 2,
        sqft: 1600,
        propertyType: 'Single Family',
        notes: 'Your closed deal — kept as a comp. Great spread realized.',
    },
    {
        id: 9,
        createdAt: daysAgo(14),
        msaId: 3,
        msaName: 'Denver-Aurora-Lakewood, CO',
        userId: 'user-g',
        userFirstName: 'Ava',
        userLastName: 'Klein',
        userEmail: 'ava@example.com',
        userPhone: '(720) 555-0110',
        links: [{ url: 'https://www.zillow.com/homedetails/aurora', domain: 'zillow' }],
        streetViewUrl: img('den-birch'),
        isArvExclusive: false,
        address: '9043 E 25th Ave',
        city: 'AURORA',
        state: 'CO',
        zipCode: '80010',
        dealType: 'agent',
        price: 340000,
        potentialARV: 465000,
        estimatedBudget: 55000,
        beds: 3,
        baths: 2,
        sqft: 1210,
        propertyType: 'Single Family',
        showingTime: '2026-07-18T10:30:00',
        notes: 'Solid starter flip near Anschutz medical campus. Rentable if the flip math tightens.',
        bidCount: 3,
    },
];

// ── Preview-only client filtering (the live page filters server-side) ────────

function matchesLocation(deal: Deal, filter: LocationFilter | null): boolean {
    if (!filter) return true;
    if (filter.type === 'zip') return deal.zipCode === filter.value;
    if (filter.type === 'city')
        return deal.city.toLowerCase() === filter.value.toLowerCase() && deal.state === filter.state;
    if (filter.type === 'msa') return (deal.msaName ?? '') === filter.value;
    if (filter.type === 'county') return (deal.county ?? '') === filter.value;
    return true;
}

/** Applies the toolbar filters to the mock set exactly as the API would, for the preview harness. */
export function filterMockDeals(opts: {
    scope: 'all' | 'mine';
    typeFilter: DealTypeFilter;
    location: LocationFilter | null;
}): Deal[] {
    return MOCK_DEALS.filter((deal) => {
        if (opts.scope === 'mine' && deal.userId !== MOCK_USER_ID) return false;
        if (opts.typeFilter !== 'all' && deal.dealType !== opts.typeFilter) return false;
        if (!matchesLocation(deal, opts.location)) return false;
        return true;
    });
}
