import { z } from "zod";

export const updatePropertySchema = z.object({
  sfrPropertyId: z.coerce.number().int().optional(),
  companyId: z.string().uuid().nullable().optional(),
  propertyClassDescription: z.string().nullable().optional(),
  propertyType: z.string().nullable().optional(),
  vacant: z.boolean().nullable().optional(),
  hoa: z.string().nullable().optional(),
  ownerType: z.string().nullable().optional(),
  purchaseMethod: z.string().nullable().optional(),
  listingStatus: z.string().nullable().optional(),
  status: z.string().nullable().optional(),
  monthsOwned: z.coerce.number().int().nullable().optional(),
  msa: z.string().nullable().optional(),
  county: z.string().nullable().optional(),
}).strict();

export const updateAddressSchema = z.object({
  formattedStreetAddress: z.string().nullable().optional(),
  streetNumber: z.string().nullable().optional(),
  streetSuffix: z.string().nullable().optional(),
  streetPreDirection: z.string().nullable().optional(),
  streetName: z.string().nullable().optional(),
  streetPostDirection: z.string().nullable().optional(),
  unitType: z.string().nullable().optional(),
  unitNumber: z.string().nullable().optional(),
  city: z.string().nullable().optional(),
  state: z.string().nullable().optional(),
  zipCode: z.string().nullable().optional(),
  zipPlusFourCode: z.string().nullable().optional(),
  carrierCode: z.string().nullable().optional(),
  latitude: z.coerce.number().nullable().optional(),
  longitude: z.coerce.number().nullable().optional(),
  geocodingAccuracy: z.string().nullable().optional(),
  censusTract: z.string().nullable().optional(),
  censusBlock: z.string().nullable().optional(),
}).strict();

export const updateStructureSchema = z.object({
  totalAreaSqFt: z.coerce.number().int().nullable().optional(),
  yearBuilt: z.coerce.number().int().nullable().optional(),
  effectiveYearBuilt: z.coerce.number().int().nullable().optional(),
  bedsCount: z.coerce.number().int().nullable().optional(),
  roomsCount: z.coerce.number().int().nullable().optional(),
  baths: z.coerce.number().nullable().optional(),
  basementType: z.string().nullable().optional(),
  condition: z.string().nullable().optional(),
  constructionType: z.string().nullable().optional(),
  exteriorWallType: z.string().nullable().optional(),
  fireplaces: z.coerce.number().int().nullable().optional(),
  heatingType: z.string().nullable().optional(),
  heatingFuelType: z.string().nullable().optional(),
  parkingSpacesCount: z.coerce.number().int().nullable().optional(),
  poolType: z.string().nullable().optional(),
  quality: z.string().nullable().optional(),
  roofMaterialType: z.string().nullable().optional(),
  roofStyleType: z.string().nullable().optional(),
  sewerType: z.string().nullable().optional(),
  stories: z.string().nullable().optional(),
  unitsCount: z.coerce.number().int().nullable().optional(),
  waterType: z.string().nullable().optional(),
  livingAreaSqft: z.coerce.number().int().nullable().optional(),
  acDescription: z.string().nullable().optional(),
  garageDescription: z.string().nullable().optional(),
  buildingClassDescription: z.string().nullable().optional(),
  sqftDescription: z.string().nullable().optional(),
}).strict();