export const MOCK_BUYER_MARKET_DATA = [
    {
        "id": 1653625,
        "propertyId": 158958673,
        "recordingDate": "2026-02-06",
        "buyerName": "NYMAN GAIL",
        "formattedBuyerName": "nyman-gail5222c5bf600012f0780e1b6288d98bf8",
        "lenderName": null,
        "address": "11560 KALISPELL ST",
        "phone": null,
        "city": "COMMERCE CITY",
        "zipCode": "80022",
        "buildingArea": 3975,
        "yearBuilt": 2019,
        "avmValue": 578113,
        "saleValue": 565000,
        "saleDate": "2026-02-05",
        "sellerName": "STILWELL BRADLEY D",
        "latitude": 39.906676,
        "longitude": -104.801342,
        "isCorporate": false,
        "isDiscountedPurchase": false,
        "isCashBuyer": true,
        "isPrivateLender": false,
        "bedrooms": 3,
        "bathrooms": 2,
        "propertyType": "Single Family Residential",
        "msa": "Denver-Aurora-Centennial, CO",
        "state": "CO",
        "loanAmount": 0,
        "buyerPropertiesCount": 1,
        "buyerTransactionsCount": 1,
        "hasProfilePage": false,
        "exitDate": null,
        "exitValue": null,
        "exitBuyerName": null,
        "profitLoss": null,
        "holdDays": null
    },
    {
        "id": 10696906,
        "propertyId": 22336346,
        "recordingDate": "2026-02-06",
        "buyerName": "PURCHASING FUND 2023-2 LLC",
        "formattedBuyerName": "purchasing-fund-2023-2-llc-co",
        "lenderName": null,
        "address": "820 E 131ST PL",
        "phone": null,
        "city": "THORNTON",
        "zipCode": "80241",
        "buildingArea": 3483,
        "yearBuilt": 1994,
        "avmValue": 670423,
        "saleValue": 650000,
        "saleDate": "2026-02-06",
        "sellerName": "JOHNSON ROSALIE",
        "latitude": 39.934463,
        "longitude": -104.977083,
        "isCorporate": true,
        "isDiscountedPurchase": false,
        "isCashBuyer": true,
        "isPrivateLender": false,
        "bedrooms": 4,
        "bathrooms": 2,
        "propertyType": "Single Family Residential",
        "msa": "Denver-Aurora-Centennial, CO",
        "state": "CO",
        "loanAmount": 0,
        "buyerPropertiesCount": 7,
        "buyerTransactionsCount": 29,
        "hasProfilePage": true,
        "exitDate": null,
        "exitValue": null,
        "exitBuyerName": null,
        "profitLoss": null,
        "holdDays": null
    },
    {
        "id": 10696075,
        "propertyId": 22356084,
        "recordingDate": "2026-02-06",
        "buyerName": "BRADBURN BUNGALOW LLC",
        "formattedBuyerName": "bradburn-bungalow-llc-co",
        "lenderName": null,
        "address": "3849 W 118TH PL",
        "phone": null,
        "city": "WESTMINSTER",
        "zipCode": "80031",
        "buildingArea": 1824,
        "yearBuilt": 2004,
        "avmValue": 465692,
        "saleValue": 440000,
        "saleDate": "2026-01-30",
        "sellerName": "BEHAN JOHN DAVID",
        "latitude": 39.911779,
        "longitude": -105.037329,
        "isCorporate": true,
        "isDiscountedPurchase": false,
        "isCashBuyer": true,
        "isPrivateLender": false,
        "bedrooms": 2,
        "bathrooms": 2,
        "propertyType": "Townhouse",
        "msa": "Denver-Aurora-Centennial, CO",
        "state": "CO",
        "loanAmount": 0,
        "buyerPropertiesCount": 1,
        "buyerTransactionsCount": 1,
        "hasProfilePage": false,
        "exitDate": null,
        "exitValue": null,
        "exitBuyerName": null,
        "profitLoss": null,
        "holdDays": null
    },
    {
        "id": 10695281,
        "propertyId": 22373306,
        "recordingDate": "2026-02-06",
        "buyerName": "COLORADO REAL ESTATE ACQUISITIONS LLC",
        "formattedBuyerName": "colorado-real-estate-acquisitions-llc-co",
        "lenderName": null,
        "address": "8191 BAYLOR LN",
        "phone": null,
        "city": "WESTMINSTER",
        "zipCode": "80031",
        "buildingArea": 1768,
        "yearBuilt": 1959,
        "avmValue": 446092,
        "saleValue": 328000,
        "saleDate": "2026-02-06",
        "sellerName": "BERING MARTHA JUNE",
        "latitude": 39.846241,
        "longitude": -105.042056,
        "isCorporate": true,
        "isDiscountedPurchase": true,
        "isCashBuyer": true,
        "isPrivateLender": false,
        "bedrooms": 2,
        "bathrooms": 2,
        "propertyType": "Single Family Residential",
        "msa": "Denver-Aurora-Centennial, CO",
        "state": "CO",
        "loanAmount": 0,
        "buyerPropertiesCount": 3,
        "buyerTransactionsCount": 18,
        "hasProfilePage": true,
        "exitDate": null,
        "exitValue": null,
        "exitBuyerName": null,
        "profitLoss": null,
        "holdDays": null
    },
    {
        "id": 10695280,
        "propertyId": 22373306,
        "recordingDate": "2026-02-06",
        "buyerName": "CLEAR SKY INNOVATIONS LLC",
        "formattedBuyerName": "clear-sky-innovations-llc-co",
        "lenderName": "HIGHLINE CAP CORPORATION",
        "address": "8191 BAYLOR LN",
        "phone": null,
        "city": "WESTMINSTER",
        "zipCode": "80031",
        "buildingArea": 1768,
        "yearBuilt": 1959,
        "avmValue": 446092,
        "saleValue": 360000,
        "saleDate": "2026-02-06",
        "sellerName": "COLORADO REAL ESTATE ACQUISITIONS LLC",
        "latitude": 39.846241,
        "longitude": -105.042056,
        "isCorporate": true,
        "isDiscountedPurchase": true,
        "isCashBuyer": false,
        "isPrivateLender": true,
        "bedrooms": 2,
        "bathrooms": 2,
        "propertyType": "Single Family Residential",
        "msa": "Denver-Aurora-Centennial, CO",
        "state": "CO",
        "loanAmount": 405000,
        "buyerPropertiesCount": 1,
        "buyerTransactionsCount": 1,
        "hasProfilePage": false,
        "exitDate": null,
        "exitValue": null,
        "exitBuyerName": null,
        "profitLoss": null,
        "holdDays": null
    }
]

export const MOCK_BATCH_LOOKUP_DATA = [
    {
        "address": "11560 KALISPELL ST, COMMERCE CITY, CO 80022",
        "property": {
            "property_id": 158958673,
            "address": {
                "formatted_street_address": "11560 KALISPELL ST",
                "street_number": "11560",
                "street_suffix": null,
                "street_pre_direction": null,
                "street_name": "KALISPELL",
                "street_post_direction": null,
                "unit_type": null,
                "unit_number": null,
                "city": "COMMERCE CITY",
                "state": "CO",
                "zip_code": "80022",
                "zip_plus_four_code": "9760",
                "carrier_code": "R012",
                "latitude": 39.906676,
                "longitude": -104.801342,
                "geocoding_accuracy": "Record was coded to the rooftop level",
                "census_tract": "008536",
                "census_block": "1021"
            },
            "assessed_year": 2025,
            "assessments": {
                "land_value": 138000,
                "improvement_value": 475000,
                "assessed_value": 41680,
                "market_value": 613000
            },
            "exemptions": {
                "homeowner": null,
                "veteran": null,
                "disabled": null,
                "widow": null,
                "senior": null,
                "school": null,
                "religious": null,
                "welfare": null,
                "public": null,
                "cemetery": null,
                "hospital": null,
                "library": null
            },
            "market_year": 2025,
            "owner": {
                "owner_occupied": true,
                "name": "GAIL NYMAN",
                "second_name": "DARYL NYMAN",
                "formatted_street_address": "11560 KALISPELL ST",
                "city": "COMMERCE CITY",
                "state": "CO",
                "zip_code": "80022",
                "zip_plus_four_code": "9760",
                "corporate_owner": false,
                "care_of_name": null
            },
            "parcel": {
                "apn_original": "R0189857",
                "fips_code": "08001",
                "frontage_ft": null,
                "depth_ft": null,
                "area_acres": "0000000213",
                "area_sq_ft": 9260,
                "zoning": null,
                "county_land_use_code": "1112",
                "lot_number": "10",
                "subdivision": "THE VILLAGES AT BUFFALO RUN EAST",
                "section_township_range": "SEC 05 QTR 3 TWN 02S RNG 66W",
                "legal_description": "THE VILLAGES AT BUFFALO RUN EAST FLG NO 7 BLK 11 LOT 10",
                "state_land_use_code": null,
                "building_count": 1
            },
            "school_tax_district_1": "SD 27-BRIGHTON",
            "school_tax_district_2": null,
            "school_tax_district_3": null,
            "school_district_name": "School District 27J",
            "structure": {
                "total_area_sq_ft": 2010,
                "year_built": 2019,
                "effective_year_built": 2019,
                "beds_count": 3,
                "rooms_count": 6,
                "baths": 2,
                "partial_baths_count": 0,
                "basement_type": "Unspecified Basement ",
                "condition": "Average",
                "construction_type": "Frame",
                "exterior_wall_type": "Siding (Alum/Vinyl)",
                "fireplaces": null,
                "heating_type": "Central",
                "heating_fuel_type": null,
                "parking_spaces_count": 2,
                "pool_type": null,
                "quality": "B",
                "roof_material_type": "Other",
                "roof_style_type": 1,
                "sewer_type": null,
                "stories": "1 Story",
                "units_count": 0,
                "water_type": null,
                "living_area_sqft": 2010,
                "ac_description": "Central",
                "garage_description": "Attached Garage",
                "building_class_description": null,
                "sqft_description": "Living Area"
            },
            "tax_amount": 675436,
            "tax_delinquent_year": null,
            "tax_rate_code_area": "10-106",
            "tax_year": 2025,
            "valuation": {
                "value": 578113,
                "high": 610813,
                "low": 545414,
                "forecast_standard_deviation": 0.0565622303028466,
                "date": "2026-01-19"
            },
            "property_class_description": "RESIDENTIAL",
            "vacant": null,
            "pre_foreclosure": {
                "flag": false,
                "ind": null,
                "reason": null,
                "doc_type": null,
                "recording_date": null
            },
            "last_sale": {
                "date": "2026-02-06",
                "price": 565000,
                "document_type": "Warranty Deed",
                "mtg_amount": 0,
                "mtg_type": null,
                "lender": null,
                "mtg_interest_rate": null,
                "mtg_term_months": null
            },
            "current_sale": {
                "doc_num": "2026.6101",
                "buyer_1": "NYMAN GAIL",
                "buyer_2": "NYMAN DARYL",
                "seller_1": "STILWELL BRADLEY D",
                "seller_2": "STILWELL SARAH B"
            },
            "msa": "Denver-Aurora-Centennial, CO",
            "county": "Adams County, Colorado",
            "property_type": "Single Family Residential",
            "hoa": "Yes",
            "owner_type": "Corporate/Trust",
            "purchase_method": "Cash",
            "listing_status": "On Market",
            "months_owned": 0
        },
        "error": null
    },
    {
        "address": "820 E 131ST PL, THORNTON, CO 80241",
        "property": {
            "property_id": 22336346,
            "address": {
                "formatted_street_address": "820 E 131ST PL",
                "street_number": "820",
                "street_suffix": null,
                "street_pre_direction": "E",
                "street_name": "131ST",
                "street_post_direction": null,
                "unit_type": null,
                "unit_number": null,
                "city": "THORNTON",
                "state": "CO",
                "zip_code": "80241",
                "zip_plus_four_code": "1130",
                "carrier_code": "C063",
                "latitude": 39.934463,
                "longitude": -104.977083,
                "geocoding_accuracy": "Record was coded to the rooftop level",
                "census_tract": "008526",
                "census_block": "5007"
            },
            "assessed_year": 2025,
            "assessments": {
                "land_value": 117000,
                "improvement_value": 544000,
                "assessed_value": 44950,
                "market_value": 661000
            },
            "exemptions": {
                "homeowner": null,
                "veteran": null,
                "disabled": null,
                "widow": null,
                "senior": null,
                "school": null,
                "religious": null,
                "welfare": null,
                "public": null,
                "cemetery": null,
                "hospital": null,
                "library": null
            },
            "market_year": 2025,
            "owner": {
                "owner_occupied": false,
                "name": "PURCHASING FUND 2023-2 LLC",
                "second_name": null,
                "formatted_street_address": "820 E 131ST PL",
                "city": "THORNTON",
                "state": "CO",
                "zip_code": "80241",
                "zip_plus_four_code": "1130",
                "corporate_owner": true,
                "care_of_name": null
            },
            "parcel": {
                "apn_original": "R0017940",
                "fips_code": "08001",
                "frontage_ft": "700",
                "depth_ft": "1110",
                "area_acres": "0000000178",
                "area_sq_ft": 7770,
                "zoning": null,
                "county_land_use_code": "1112",
                "lot_number": "36",
                "subdivision": "HUNTERS GLEN II A- PUD",
                "section_township_range": "SEC 26 QTR 3 TWN 01S RNG 68W",
                "legal_description": "SUB:HUNTERS GLEN II A- PUD BLK:3 LOT:36",
                "state_land_use_code": null,
                "building_count": 1
            },
            "school_tax_district_1": "SD 12",
            "school_tax_district_2": null,
            "school_tax_district_3": null,
            "school_district_name": "Adams 12 Five Star Schools",
            "structure": {
                "total_area_sq_ft": 2883,
                "year_built": 1994,
                "effective_year_built": 2019,
                "beds_count": 4,
                "rooms_count": 7,
                "baths": 2,
                "partial_baths_count": 1,
                "basement_type": "Improved Basement (Finished)",
                "condition": "Good",
                "construction_type": "Frame",
                "exterior_wall_type": "Siding (Alum/Vinyl)",
                "fireplaces": 1,
                "heating_type": "Central",
                "heating_fuel_type": null,
                "parking_spaces_count": 2,
                "pool_type": null,
                "quality": "B",
                "roof_material_type": "Composition Shingle",
                "roof_style_type": 1,
                "sewer_type": null,
                "stories": "2 Stories",
                "units_count": 1,
                "water_type": null,
                "living_area_sqft": 2883,
                "ac_description": "Central",
                "garage_description": "Attached Garage",
                "building_class_description": null,
                "sqft_description": "Living Area"
            },
            "tax_amount": 505832,
            "tax_delinquent_year": null,
            "tax_rate_code_area": "18-180",
            "tax_year": 2025,
            "valuation": {
                "value": 670423,
                "high": 750933,
                "low": 589913,
                "forecast_standard_deviation": 0.120088309613463,
                "date": "2026-01-19"
            },
            "property_class_description": "RESIDENTIAL",
            "vacant": null,
            "pre_foreclosure": {
                "flag": false,
                "ind": null,
                "reason": null,
                "doc_type": null,
                "recording_date": null
            },
            "last_sale": {
                "date": "2026-02-06",
                "price": 650000,
                "document_type": "Warranty Deed",
                "mtg_amount": 0,
                "mtg_type": null,
                "lender": null,
                "mtg_interest_rate": null,
                "mtg_term_months": null
            },
            "current_sale": {
                "doc_num": "2026.6196",
                "buyer_1": "PURCHASING FUND 2023-2 LLC",
                "buyer_2": null,
                "seller_1": "JOHNSON ROSALIE",
                "seller_2": null
            },
            "msa": "Denver-Aurora-Centennial, CO",
            "county": "Adams County, Colorado",
            "property_type": "Single Family Residential",
            "hoa": "Yes",
            "owner_type": "Individual",
            "purchase_method": "Cash",
            "listing_status": "Off Market",
            "months_owned": 0
        },
        "error": null
    },
    {
        "address": "3849 W 118TH PL, WESTMINSTER, CO 80031",
        "property": {
            "property_id": 22356084,
            "address": {
                "formatted_street_address": "3849 W 118TH PL",
                "street_number": "3849",
                "street_suffix": null,
                "street_pre_direction": "W",
                "street_name": "118TH",
                "street_post_direction": null,
                "unit_type": null,
                "unit_number": null,
                "city": "WESTMINSTER",
                "state": "CO",
                "zip_code": "80031",
                "zip_plus_four_code": "5033",
                "carrier_code": "C043",
                "latitude": 39.911779,
                "longitude": -105.037329,
                "geocoding_accuracy": "Record was coded to the rooftop level",
                "census_tract": "009408",
                "census_block": "1027"
            },
            "assessed_year": 2025,
            "assessments": {
                "land_value": 110000,
                "improvement_value": 367000,
                "assessed_value": 32440,
                "market_value": 477000
            },
            "exemptions": {
                "homeowner": null,
                "veteran": null,
                "disabled": null,
                "widow": null,
                "senior": null,
                "school": null,
                "religious": null,
                "welfare": null,
                "public": null,
                "cemetery": null,
                "hospital": null,
                "library": null
            },
            "market_year": 2025,
            "owner": {
                "owner_occupied": false,
                "name": "BRADBURN BUNGALOW LLC",
                "second_name": null,
                "formatted_street_address": "PO BOX 351614",
                "city": "WESTMINSTER",
                "state": "CO",
                "zip_code": "80035",
                "zip_plus_four_code": "1614",
                "corporate_owner": true,
                "care_of_name": null
            },
            "parcel": {
                "apn_original": "R0158234",
                "fips_code": "08001",
                "frontage_ft": null,
                "depth_ft": null,
                "area_acres": "0000000035",
                "area_sq_ft": 1504,
                "zoning": null,
                "county_land_use_code": "1114",
                "lot_number": "33",
                "subdivision": "BRADBURN",
                "section_township_range": "SEC 06 QTR 1 TWN 02S RNG 68W",
                "legal_description": "SUB:BRADBURN SUBD FILING NO 1 3RD REPLAT BLK:19 LOT:33",
                "state_land_use_code": null,
                "building_count": 1
            },
            "school_tax_district_1": "SD 12",
            "school_tax_district_2": null,
            "school_tax_district_3": null,
            "school_district_name": "Adams 12 Five Star Schools",
            "structure": {
                "total_area_sq_ft": 1216,
                "year_built": 2004,
                "effective_year_built": 2004,
                "beds_count": 2,
                "rooms_count": 5,
                "baths": 2,
                "partial_baths_count": 1,
                "basement_type": "Unspecified Basement ",
                "condition": "Average",
                "construction_type": "Frame",
                "exterior_wall_type": "Combination",
                "fireplaces": null,
                "heating_type": "Forced air unit",
                "heating_fuel_type": null,
                "parking_spaces_count": 1,
                "pool_type": null,
                "quality": "B",
                "roof_material_type": "Composition Shingle",
                "roof_style_type": 1,
                "sewer_type": null,
                "stories": "2 Stories",
                "units_count": 5,
                "water_type": null,
                "living_area_sqft": 1216,
                "ac_description": "Central",
                "garage_description": "Detached Garage",
                "building_class_description": null,
                "sqft_description": "Living Area"
            },
            "tax_amount": 471846,
            "tax_delinquent_year": null,
            "tax_rate_code_area": "16-168",
            "tax_year": 2025,
            "valuation": {
                "value": 465692,
                "high": 492033,
                "low": 439352,
                "forecast_standard_deviation": 0.0565622303028466,
                "date": "2026-01-19"
            },
            "property_class_description": "RESIDENTIAL",
            "vacant": null,
            "pre_foreclosure": {
                "flag": false,
                "ind": null,
                "reason": null,
                "doc_type": null,
                "recording_date": null
            },
            "last_sale": {
                "date": "2026-02-06",
                "price": 440000,
                "document_type": "Warranty Deed",
                "mtg_amount": 0,
                "mtg_type": null,
                "lender": null,
                "mtg_interest_rate": null,
                "mtg_term_months": null
            },
            "current_sale": {
                "doc_num": "2026.6106",
                "buyer_1": "BRADBURN BUNGALOW LLC",
                "buyer_2": null,
                "seller_1": "BEHAN JOHN DAVID",
                "seller_2": "BERNAL CARLY ROSE"
            },
            "msa": "Denver-Aurora-Centennial, CO",
            "county": "Adams County, Colorado",
            "property_type": "Townhouse (Residential)",
            "hoa": "Yes",
            "owner_type": "Individual",
            "purchase_method": "Cash",
            "listing_status": "Off Market",
            "months_owned": 0
        },
        "error": null
    },
    {
        "address": "8191 BAYLOR LN, WESTMINSTER, CO 80031",
        "property": {
            "property_id": 22373306,
            "address": {
                "formatted_street_address": "8191 BAYLOR LN",
                "street_number": "8191",
                "street_suffix": null,
                "street_pre_direction": null,
                "street_name": "BAYLOR",
                "street_post_direction": null,
                "unit_type": null,
                "unit_number": null,
                "city": "WESTMINSTER",
                "state": "CO",
                "zip_code": "80031",
                "zip_plus_four_code": "3952",
                "carrier_code": "C012",
                "latitude": 39.846241,
                "longitude": -105.042056,
                "geocoding_accuracy": "Record was coded to the rooftop level",
                "census_tract": "009401",
                "census_block": "2009"
            },
            "assessed_year": 2025,
            "assessments": {
                "land_value": 90000,
                "improvement_value": 337000,
                "assessed_value": 29040,
                "market_value": 427000
            },
            "exemptions": {
                "homeowner": null,
                "veteran": null,
                "disabled": null,
                "widow": null,
                "senior": null,
                "school": null,
                "religious": null,
                "welfare": null,
                "public": null,
                "cemetery": null,
                "hospital": null,
                "library": null
            },
            "market_year": 2025,
            "owner": {
                "owner_occupied": false,
                "name": "CLEAR SKY INNOVATIONS LLC",
                "second_name": null,
                "formatted_street_address": "15200 E STANFORD PL",
                "city": "AURORA",
                "state": "CO",
                "zip_code": "80015",
                "zip_plus_four_code": "1328",
                "corporate_owner": true,
                "care_of_name": null
            },
            "parcel": {
                "apn_original": "R0063348",
                "fips_code": "08001",
                "frontage_ft": "630",
                "depth_ft": "1400",
                "area_acres": "0000000203",
                "area_sq_ft": 8820,
                "zoning": null,
                "county_land_use_code": "1112",
                "lot_number": "11",
                "subdivision": "SHAW HEIGHTS FIFTH FILING",
                "section_township_range": "SEC 30 QTR 4 TWN 02S RNG 68W",
                "legal_description": "SUB:SHAW HEIGHTS FIFTH FILING BLK:96 LOT:11",
                "state_land_use_code": null,
                "building_count": 1
            },
            "school_tax_district_1": "WESTMINSTER PUB",
            "school_tax_district_2": null,
            "school_tax_district_3": null,
            "school_district_name": "Westminster Public School District",
            "structure": {
                "total_area_sq_ft": 884,
                "year_built": 1959,
                "effective_year_built": 1959,
                "beds_count": 2,
                "rooms_count": 4,
                "baths": 2,
                "partial_baths_count": 0,
                "basement_type": "Unspecified Basement ",
                "condition": "Average",
                "construction_type": "Frame",
                "exterior_wall_type": "Combination",
                "fireplaces": null,
                "heating_type": "Forced air unit",
                "heating_fuel_type": null,
                "parking_spaces_count": 2,
                "pool_type": null,
                "quality": "D",
                "roof_material_type": "Composition Shingle",
                "roof_style_type": 7,
                "sewer_type": null,
                "stories": "1 Story",
                "units_count": 1,
                "water_type": null,
                "living_area_sqft": 884,
                "ac_description": "Central",
                "garage_description": "Detached Garage",
                "building_class_description": null,
                "sqft_description": "Living Area"
            },
            "tax_amount": 209154,
            "tax_delinquent_year": null,
            "tax_rate_code_area": "55-555",
            "tax_year": 2025,
            "valuation": {
                "value": 446092,
                "high": 502787,
                "low": 389397,
                "forecast_standard_deviation": 0.127093382801666,
                "date": "2026-01-19"
            },
            "property_class_description": "RESIDENTIAL",
            "vacant": null,
            "pre_foreclosure": {
                "flag": false,
                "ind": null,
                "reason": null,
                "doc_type": null,
                "recording_date": null
            },
            "last_sale": {
                "date": "2026-02-06",
                "price": 360000,
                "document_type": "Special Warranty Deed",
                "mtg_amount": 405000,
                "mtg_type": "Building or Construction Loan",
                "lender": "HIGHLINE CAP CORPORATION",
                "mtg_interest_rate": " 01100",
                "mtg_term_months": "6"
            },
            "current_sale": {
                "doc_num": "2026.6245",
                "buyer_1": "CLEAR SKY INNOVATIONS LLC",
                "buyer_2": null,
                "seller_1": "COLORADO REAL ESTATE ACQUISITIONS LLC",
                "seller_2": null
            },
            "msa": "Denver-Aurora-Centennial, CO",
            "county": "Adams County, Colorado",
            "property_type": "Single Family Residential",
            "hoa": "Yes",
            "owner_type": "Individual",
            "purchase_method": "Financed",
            "listing_status": "Off Market",
            "months_owned": 0
        },
        "error": null
    }
]

export const MOCK_PROPERTY_TRANSACTIONS_DATA = {
    "property_id": 158958673,
    "address": "11560 KALISPELL ST",
    "transactions": [
        {
            "RECORDING_DATE": "2026-02-06",
            "APN": "R0189857",
            "BUYER_BORROWER1_NAME": "NYMAN GAIL",
            "BUYER_BORROWER2_NAME": "NYMAN DARYL",
            "SALE_DATE": "2026-02-05",
            "TRANSACTION_TYPE": "Arms Length",
            "SELLER1_NAME": "STILWELL BRADLEY D",
            "SALE_AMT": "565000",
            "FIRST_MTG_RECORDING_DATE": null,
            "FIRST_MTG_AMT": 0,
            "FIRST_MTG_LENDER_NAME": null,
            "FIRST_MTG_DUE_DATE": null
        },
        {
            "RECORDING_DATE": "2021-11-09",
            "APN": "R0189857",
            "BUYER_BORROWER1_NAME": "STILWELL BRADLEY D",
            "BUYER_BORROWER2_NAME": "STILWELL SARAH B",
            "SALE_DATE": "2021-11-03",
            "TRANSACTION_TYPE": "REFI LOANS and 2ND TRUST DEEDS",
            "SELLER1_NAME": null,
            "SALE_AMT": null,
            "FIRST_MTG_RECORDING_DATE": "2021-11-09",
            "FIRST_MTG_AMT": 559440,
            "FIRST_MTG_LENDER_NAME": "COLTEN MORTGAGE",
            "FIRST_MTG_DUE_DATE": "2051-12-01"
        },
        {
            "RECORDING_DATE": "2021-03-03",
            "APN": "R0189857",
            "BUYER_BORROWER1_NAME": "STILWELL BRADLEY D",
            "BUYER_BORROWER2_NAME": "STILWELL SARAH B",
            "SALE_DATE": "2021-02-23",
            "TRANSACTION_TYPE": "REFI LOANS and 2ND TRUST DEEDS",
            "SELLER1_NAME": null,
            "SALE_AMT": null,
            "FIRST_MTG_RECORDING_DATE": "2021-03-03",
            "FIRST_MTG_AMT": 427987,
            "FIRST_MTG_LENDER_NAME": "PLANET HOME LENDING LLC",
            "FIRST_MTG_DUE_DATE": "2051-03-01"
        },
        {
            "RECORDING_DATE": "2020-03-04",
            "APN": "R0189857",
            "BUYER_BORROWER1_NAME": "STILWELL BRADLEY D",
            "BUYER_BORROWER2_NAME": "STILWELL SARAH B",
            "SALE_DATE": "2020-02-28",
            "TRANSACTION_TYPE": "Arms Length",
            "SELLER1_NAME": "LOKAL BR7 LLC",
            "SALE_AMT": "427811",
            "FIRST_MTG_RECORDING_DATE": "2020-03-04",
            "FIRST_MTG_AMT": 431411,
            "FIRST_MTG_LENDER_NAME": "COLTEN MORTGAGE",
            "FIRST_MTG_DUE_DATE": "2050-03-01"
        }
    ]
}