const COUNTY_TO_MSA: Record<string, string> = {
    "San Diego":     "San Diego-Chula Vista-Carlsbad, CA",
    "Los Angeles":   "Los Angeles-Long Beach-Anaheim, CA",
    "Orange":        "Los Angeles-Long Beach-Anaheim, CA",
    "Denver":        "Denver-Aurora-Centennial, CO",
    "Adams":         "Denver-Aurora-Centennial, CO",
    "Arapahoe":      "Denver-Aurora-Centennial, CO",
    "Broomfield":    "Denver-Aurora-Centennial, CO",
    "Jefferson":     "Denver-Aurora-Centennial, CO",
    "Douglas":       "Denver-Aurora-Centennial, CO",
    "Clear Creek":   "Denver-Aurora-Centennial, CO",
    "Gilpin":        "Denver-Aurora-Centennial, CO",
    "Elbert":        "Denver-Aurora-Centennial, CO",
    "Park":          "Denver-Aurora-Centennial, CO",
    "San Francisco": "San Francisco-Oakland-Fremont, CA",
    "Alameda":       "San Francisco-Oakland-Fremont, CA",
    "Contra Costa":  "San Francisco-Oakland-Fremont, CA",
    "Marin":         "San Francisco-Oakland-Fremont, CA",
    "San Mateo":     "San Francisco-Oakland-Fremont, CA",
    "Miami-Dade":    "Miami-Fort Lauderdale-West Palm Beach, FL",
    "Broward":       "Miami-Fort Lauderdale-West Palm Beach, FL",
    "Palm Beach":    "Miami-Fort Lauderdale-West Palm Beach, FL",
    "St. Lucie":     "Port St. Lucie, FL",
    "Martin":        "Port St. Lucie, FL",
    "King":          "Seattle-Tacoma-Bellevue, WA",
    "Pierce":        "Seattle-Tacoma-Bellevue, WA",
    "Snohomish":     "Seattle-Tacoma-Bellevue, WA",
    "Hillsborough":  "Tampa-St. Petersburg-Clearwater, FL",
    "Pinellas":      "Tampa-St. Petersburg-Clearwater, FL",
    "Pasco":         "Tampa-St. Petersburg-Clearwater, FL",
    "Hernando":      "Tampa-St. Petersburg-Clearwater, FL",
};

export function getMsaNameFromCounty(county: string): string | undefined {
    return COUNTY_TO_MSA[county];
}
